apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pokemon
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    spec:
      containers:
      - image: gcr.io/manifest-setup-447710-h7/pokemon:latest