import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}> 
      <div className="flex gap-4 p-8">
          <Image
            src='/pokemon.svg'
            alt="Pokemon Logo"
            width={200}
            height={24}
          />
        </div>    
        {modal}
        {children}        
      </body>
    </html>
  );
}
